spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample?characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update